// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"


type BuilderInfo struct {
	B string `json:"b"`
	F int `json:"f"`
}

type Candle struct {
	T int `json:"T"`
	C string `json:"c"`
	H string `json:"h"`
	I string `json:"i"`
	L string `json:"l"`
	N int `json:"n"`
	O string `json:"o"`
	S string `json:"s"`
	V string `json:"v"`
}

type ClearinghouseState struct {
	AssetPositions json.RawMessage `json:"assetPositions"`
	CrossMaintenanceMarginUsed string `json:"crossMaintenanceMarginUsed"`
	CrossMarginSummary json.RawMessage `json:"crossMarginSummary"`
	MarginSummary json.RawMessage `json:"marginSummary"`
	Time int `json:"time"`
	Withdrawable string `json:"withdrawable"`
}

type ExchangeApproveAgentResponse struct {
}

type ExchangeApproveBuilderFeeResponse struct {
}

type ExchangeBatchModifyOrdersResponse struct {
}

type ExchangeCancelOrdersByCloidResponse struct {
}

type ExchangeCancelOrdersResponse struct {
}

type ExchangeCancelTwapOrderResponse struct {
}

type ExchangeClassTransferResponse struct {
}

type ExchangeDelegateTokenResponse struct {
}

type ExchangeModifyOrderResponse struct {
}

type ExchangePlaceOrderResponse struct {
}

type ExchangePlaceTwapOrderResponse struct {
}

type ExchangeScheduleCancelResponse struct {
}

type ExchangeSendSpotResponse struct {
}

type ExchangeSendUsdResponse struct {
}

type ExchangeStakeDepositResponse struct {
}

type ExchangeStakeWithdrawResponse struct {
}

type ExchangeUpdateIsolatedMarginResponse struct {
}

type ExchangeUpdateLeverageResponse struct {
}

type ExchangeVaultTransferResponse struct {
}

type ExchangeWithdrawResponse struct {
}

type Fill struct {
	BuilderFee string `json:"builderFee"`
	ClosedPnl string `json:"closedPnl"`
	Coin string `json:"coin"`
	Crossed bool `json:"crossed"`
	Dir string `json:"dir"`
	Fee string `json:"fee"`
	FeeToken string `json:"feeToken"`
	Hash string `json:"hash"`
	Oid int `json:"oid"`
	Px string `json:"px"`
	Side string `json:"side"`
	StartPosition string `json:"startPosition"`
	Sz string `json:"sz"`
	Tid int `json:"tid"`
	Time int `json:"time"`
}

type FundingPoint struct {
	Coin string `json:"coin"`
	FundingRate string `json:"fundingRate"`
	Premium string `json:"premium"`
	Time int `json:"time"`
}

type InfoGetAllMidsResponse struct {
}

type InfoGetFrontendOpenOrdersItem struct {
}

type InfoGetHistoricalOrdersItem struct {
}

type InfoGetOrderStatusResponse struct {
}

type InfoGetPerpMetaAndAssetCtxsItem struct {
}

type InfoGetReferralResponse struct {
}

type InfoGetSpotClearinghouseStateResponse struct {
}

type InfoGetSpotMetaResponse struct {
}

type InfoGetUserFeesResponse struct {
}

type InfoGetUserFundingItem struct {
}

type InfoGetUserNonFundingLedgerUpdatesItem struct {
}

type InfoGetUserRoleResponse struct {
}

type InfoGetVaultDetailsResponse struct {
}

type L2Book struct {
	Coin string `json:"coin"`
	Levels json.RawMessage `json:"levels"`
	Time int `json:"time"`
}

type Meta struct {
	Universe json.RawMessage `json:"universe"`
}

type OpenOrder struct {
	Coin string `json:"coin"`
	LimitPx string `json:"limitPx"`
	Oid int `json:"oid"`
	Side string `json:"side"`
	Sz string `json:"sz"`
	Timestamp int `json:"timestamp"`
}

type OrderRequest struct {
	A int `json:"a"`
	B bool `json:"b"`
	C string `json:"c"`
	P string `json:"p"`
	R bool `json:"r"`
	S string `json:"s"`
	T json.RawMessage `json:"t"`
}
