// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"hyperliquid-pp-cli/internal/cli"
	"hyperliquid-pp-cli/internal/client"
	"hyperliquid-pp-cli/internal/config"
	"hyperliquid-pp-cli/internal/mcp/cobratree"
	"hyperliquid-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("info_get-all-mids",
			mcplib.WithDescription("All mid prices. Optional: dex. Returns the new InfoGetAllMidsResponse."),
			mcplib.WithString("dex", mcplib.Description("Dex")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/allMids", []mcpParamBinding{{PublicName: "dex", WireName: "dex", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-candle-snapshot",
			mcplib.WithDescription("Candles for a coin and interval. Required: req. Returns array of Candle."),
			mcplib.WithString("req", mcplib.Required(), mcplib.Description("Req")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/candleSnapshot", []mcpParamBinding{{PublicName: "req", WireName: "req", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-clearinghouse-state",
			mcplib.WithDescription("Perp positions, margin summary, withdrawable. Required: user. Optional: dex. Returns the new ClearinghouseState."),
			mcplib.WithString("dex", mcplib.Description("Dex")),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/clearinghouseState", []mcpParamBinding{{PublicName: "dex", WireName: "dex", Location: "body"},{PublicName: "user", WireName: "user", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-funding-history",
			mcplib.WithDescription("Historical funding rates for a coin. Required: coin, startTime. Optional: endTime. Returns array of FundingPoint."),
			mcplib.WithString("coin", mcplib.Required(), mcplib.Description("Coin")),
			mcplib.WithString("endTime", mcplib.Description("End time")),
			mcplib.WithString("startTime", mcplib.Required(), mcplib.Description("Start time")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/fundingHistory", []mcpParamBinding{{PublicName: "coin", WireName: "coin", Location: "body"},{PublicName: "endTime", WireName: "endTime", Location: "body"},{PublicName: "startTime", WireName: "startTime", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-l2-book",
			mcplib.WithDescription("L2 order book for a coin. Required: coin. Optional: mantissa, nSigFigs. Returns the new L2Book."),
			mcplib.WithString("coin", mcplib.Required(), mcplib.Description("Coin")),
			mcplib.WithString("mantissa", mcplib.Description("Mantissa")),
			mcplib.WithString("nSigFigs", mcplib.Description("N sig figs")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/l2Book", []mcpParamBinding{{PublicName: "coin", WireName: "coin", Location: "body"},{PublicName: "mantissa", WireName: "mantissa", Location: "body"},{PublicName: "nSigFigs", WireName: "nSigFigs", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-open-orders",
			mcplib.WithDescription("User's open orders (compact form). Required: user. Optional: dex. Returns array of OpenOrder."),
			mcplib.WithString("dex", mcplib.Description("Dex")),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/openOrders", []mcpParamBinding{{PublicName: "dex", WireName: "dex", Location: "body"},{PublicName: "user", WireName: "user", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-perp-meta",
			mcplib.WithDescription("Get perpetuals universe and margin tables. Optional: dex. Returns the new Meta."),
			mcplib.WithString("dex", mcplib.Description("Dex")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/meta", []mcpParamBinding{{PublicName: "dex", WireName: "dex", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-portfolio",
			mcplib.WithDescription("Account value and PnL history (day/week/month/allTime). Required: user. Returns array of InfoGetPortfolioItem."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/portfolio", []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-spot-clearinghouse-state",
			mcplib.WithDescription("Spot balances. Required: user. Returns the new InfoGetSpotClearinghouseStateResponse."),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/spotClearinghouseState", []mcpParamBinding{{PublicName: "user", WireName: "user", Location: "body"}, }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("info_get-user-fills",
			mcplib.WithDescription("User fills (most recent ~2000). Required: user. Optional: aggregateByTime (default: false). Returns array of Fill."),
			mcplib.WithString("aggregateByTime", mcplib.Description("Aggregate by time")),
			mcplib.WithString("user", mcplib.Required(), mcplib.Description("User")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
			mcplib.WithReadOnlyHintAnnotation(true),
		),
		makeAPIHandler("POST", "/info/userFills", []mcpParamBinding{{PublicName: "aggregateByTime", WireName: "aggregateByTime", Location: "body"},{PublicName: "user", WireName: "user", Location: "body"}, }, []string{ }),
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		// Hyperliquid wire reality: it has only one read endpoint (/info)
		// and one write endpoint (/exchange). Both dispatch based on a "type"
		// field in the request body. Our spec models each action as its own
		// path for command generation, so collapse those back to the bare
		// endpoint at send time. The CLI commands already do this; the MCP
		// server's makeAPIHandler missed it before. Without this rewrite
		// every info_* tool 404s.
		if method == "POST" && strings.HasPrefix(path, "/info/") {
			bodyArgs["type"] = strings.TrimPrefix(path, "/info/")
			path = "/info"
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			// Pass the map directly. c.Post calls json.Marshal internally;
			// pre-marshaling here would result in []byte being treated as
			// base64-encoded string by the inner Marshal — wire body becomes
			// a JSON string instead of an object → Hyperliquid 422.
			data, _, err = c.Post(path, bodyArgs)
		case "PUT":
			data, _, err = c.Put(path, bodyArgs)
		case "PATCH":
			data, _, err = c.Patch(path, bodyArgs)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'hyperliquid-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'hyperliquid-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "hyperliquid-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "hyperliquid-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "hyperliquid",
		"description": "Hyperliquid is an on-chain order-book L1 for perpetuals and spot. Two physical HTTP endpoints — POST /info (read) and POST /exchange (write/signed). Both dispatch on a 'type' field in the body.",
		"setup_already_complete": "If you can call exchange_* tools, the user has already generated a trading agent locally and has on-chain approved both the agent and the builder fee. Don't re-suggest those flows. Just trade.",

		"unified_account_mode": map[string]any{
			"summary": "Hyperliquid uses Unified Account Mode by default for newer users. In this mode, spot USDC and perp margin share one balance — there is NO separate perp account to fund.",
			"behavior": []string{
				"info_get-clearinghouse-state may report account_value=0 and assetPositions=[] even when the user has buying power, because perp draws from the unified pool on demand.",
				"info_get-spot-clearinghouse-state shows the user's USDC balance — that's the buying power for perp trades too.",
				"Trades placed via exchange_place_order with sufficient unified-account collateral succeed without any prior 'transfer' or 'class-transfer' action.",
			},
			"agent_pitfall": "Do NOT suggest exchange_class-transfer or 'move USDC from spot to perp' when the user wants to trade perps with a spot balance. That advice is for the (rare) non-unified mode. The default is unified.",
			"how_to_check": "POST /info {\"type\":\"userAbstraction\", \"user\": \"<addr>\"} returns 'unifiedAccount' | 'portfolioMargin' | 'default' | 'disabled' | 'dexAbstraction'. Most retail users are on 'unifiedAccount'.",
		},

		"trade_signing": map[string]any{
			"summary": "Trade-side tools (exchange_*) shell out to the local CLI binary, which loads the user's agent key and signs an EIP-712 phantom-agent envelope per Hyperliquid's L1 action spec.",
			"agent_constraints": []string{
				"The agent CAN: place, modify, cancel orders. Charge builder fees.",
				"The agent CANNOT: withdraw, transfer USDC, approve more agents. Hyperliquid enforces this server-side.",
			},
		},

		"sizing": map[string]any{
			"min_order_value_usd": 10,
			"asset_indices":       "Get from info_get-perp-meta — each universe entry has a name; the array index is the asset's 'a' value in order payloads. Also returns szDecimals per asset, which controls rounding (see precision_rules below).",
			"price_format":        "Always wire-encoded as a string, never a number. Strip trailing zeros after the decimal point (the CLI's NormalizeDecimal already does this when constructing the action).",
			"leverage":            "Set with exchange_update_leverage before placing the order. Cross is the safer default; isolated requires updateIsolatedMargin to fund.",
			"precision_rules": map[string]any{
				"summary": "Each asset has a szDecimals value (from info_get-perp-meta or spot-meta). It limits BOTH the size's decimal places AND the price's decimal places. Send too many decimals and HL rejects with 'Price must be divisible by tick size' or 'Size has too many decimal places'.",
				"size_rule":  "Size must have at most szDecimals decimal places. e.g., HYPE has szDecimals=2 → size 0.57 OK, 0.575 NOT OK.",
				"price_rule": "Price must have at most (MAX_DECIMALS - szDecimals) decimal places where MAX_DECIMALS=6 for perps, 8 for spot. e.g., HYPE perp (szDecimals=2) → max 4 decimals → 42.9525 OK, 42.95251 NOT OK. Plus a hard cap of 5 significant figures total.",
				"workflow": []string{
					"1. Call info_get-perp-meta and find the entry whose 'name' matches the user's coin",
					"2. Note its array index — that's the 'a' field value",
					"3. Note its szDecimals — call it sd",
					"4. Round size to sd decimal places",
					"5. Round price to (6 - sd) decimal places for perps OR (8 - sd) for spot",
					"6. Pass both as STRINGS in the orders array",
				},
				"examples": []map[string]string{
					{"asset": "BTC perp", "szDecimals": "5", "price_decimals": "1", "valid_size": "0.00012",   "valid_price": "70250.5"},
					{"asset": "ETH perp", "szDecimals": "4", "price_decimals": "2", "valid_size": "0.0123",    "valid_price": "3450.25"},
					{"asset": "HYPE perp","szDecimals": "2", "price_decimals": "4", "valid_size": "0.57",      "valid_price": "42.9525"},
				},
			},
		},

		"common_workflows": []map[string]string{
			{"goal": "show user's positions",      "calls": "info_get-clearinghouse-state + info_get-spot-clearinghouse-state (both — unified mode hides funds in spot)"},
			{"goal": "show user's recent trades",  "calls": "info_get-user-fills"},
			{"goal": "show open orders",           "calls": "info_get-open-orders"},
			{"goal": "place a perp market order", "calls": "info_get-perp-meta (for asset index) + info_get-all-mids (for current price) + exchange_update_leverage (set leverage) + exchange_place_order (IOC limit at slippage band acts as market)"},
			{"goal": "cancel an order",            "calls": "exchange_cancel_orders with [{a:assetIdx, o:oid}]"},
			{"goal": "show PnL",                   "calls": "info_get-portfolio (returns day/week/month/allTime), or compute from info_get-user-fills"},
		},

		"query_tips": []string{
			"All read-side tools take a 'user' arg (the wallet's 0x address). They never auth; pass any address you want to inspect.",
			"There's no pagination in the REST API. Time-bounded queries (userFillsByTime, userFunding) take startTime/endTime in ms epoch.",
			"For a market order, use a Limit IOC order with price set ~5% beyond the spread (above mark for buys, below for sells).",
			"Hyperliquid is POST-only. Do not attempt GET requests against this API.",
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
