// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newExchangeCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "exchange",
		Short: "Manage exchange",
	}

	cmd.AddCommand(newExchangeApproveAgentCmd(flags))
	cmd.AddCommand(newExchangeApproveBuilderFeeCmd(flags))
	cmd.AddCommand(newExchangeBatchModifyOrdersCmd(flags))
	cmd.AddCommand(newExchangeCancelOrdersCmd(flags))
	cmd.AddCommand(newExchangeCancelOrdersByCloidCmd(flags))
	cmd.AddCommand(newExchangeCancelTwapOrderCmd(flags))
	cmd.AddCommand(newExchangeClassTransferCmd(flags))
	cmd.AddCommand(newExchangeDelegateTokenCmd(flags))
	cmd.AddCommand(newExchangeModifyOrderCmd(flags))
	cmd.AddCommand(newExchangePlaceOrderCmd(flags))
	cmd.AddCommand(newExchangePlaceTwapOrderCmd(flags))
	cmd.AddCommand(newExchangeScheduleCancelCmd(flags))
	cmd.AddCommand(newExchangeSendSpotCmd(flags))
	cmd.AddCommand(newExchangeSendUsdCmd(flags))
	cmd.AddCommand(newExchangeStakeDepositCmd(flags))
	cmd.AddCommand(newExchangeStakeWithdrawCmd(flags))
	cmd.AddCommand(newExchangeUpdateIsolatedMarginCmd(flags))
	cmd.AddCommand(newExchangeUpdateLeverageCmd(flags))
	cmd.AddCommand(newExchangeVaultTransferCmd(flags))
	cmd.AddCommand(newExchangeWithdrawCmd(flags))
	return cmd
}
