// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInfoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Read-only queries against /info",
	}

	cmd.AddCommand(newInfoGetAllMidsCmd(flags))
	cmd.AddCommand(newInfoGetApprovedBuildersCmd(flags))
	cmd.AddCommand(newInfoGetCandleSnapshotCmd(flags))
	cmd.AddCommand(newInfoGetClearinghouseStateCmd(flags))
	cmd.AddCommand(newInfoGetFrontendOpenOrdersCmd(flags))
	cmd.AddCommand(newInfoGetFundingHistoryCmd(flags))
	cmd.AddCommand(newInfoGetHistoricalOrdersCmd(flags))
	cmd.AddCommand(newInfoGetL2BookCmd(flags))
	cmd.AddCommand(newInfoGetMaxBuilderFeeCmd(flags))
	cmd.AddCommand(newInfoGetOpenOrdersCmd(flags))
	cmd.AddCommand(newInfoGetOrderStatusCmd(flags))
	cmd.AddCommand(newInfoGetPerpMetaCmd(flags))
	cmd.AddCommand(newInfoGetPerpMetaAndAssetCtxsCmd(flags))
	cmd.AddCommand(newInfoGetPerpsAtOpenInterestCapCmd(flags))
	cmd.AddCommand(newInfoGetPortfolioCmd(flags))
	cmd.AddCommand(newInfoGetPredictedFundingsCmd(flags))
	cmd.AddCommand(newInfoGetReferralCmd(flags))
	cmd.AddCommand(newInfoGetSpotClearinghouseStateCmd(flags))
	cmd.AddCommand(newInfoGetSpotMetaCmd(flags))
	cmd.AddCommand(newInfoGetSpotMetaAndAssetCtxsCmd(flags))
	cmd.AddCommand(newInfoGetSubAccountsCmd(flags))
	cmd.AddCommand(newInfoGetUserFeesCmd(flags))
	cmd.AddCommand(newInfoGetUserFillsCmd(flags))
	cmd.AddCommand(newInfoGetUserFillsByTimeCmd(flags))
	cmd.AddCommand(newInfoGetUserFundingCmd(flags))
	cmd.AddCommand(newInfoGetUserNonFundingLedgerUpdatesCmd(flags))
	cmd.AddCommand(newInfoGetUserRoleCmd(flags))
	cmd.AddCommand(newInfoGetUserVaultEquitiesCmd(flags))
	cmd.AddCommand(newInfoGetVaultDetailsCmd(flags))
	return cmd
}
