// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

type Config struct {
	BaseURL        string `toml:"base_url"`
	AuthHeaderVal  string `toml:"auth_header"`
	AuthSource     string `toml:"-"`
	Path           string `toml:"-"`

	// Wallet configuration. The CLI signs L1 actions with whichever key is
	// active; main-only actions (approveAgent, approveBuilderFee, withdraw3,
	// usdSend, spotSend) ALWAYS require the main key regardless of Wallet.
	//
	// Wallet selects the default for trading actions (place-order, cancel,
	// modify, twap, leverage, margin): "agent" (recommended, default) or
	// "main". Override per-call with --wallet.
	Wallet         string `toml:"wallet"`
	AgentKeyPath   string `toml:"agent_key_path"`
	MainKeyPath    string `toml:"main_key_path"`
	IsMainnet      bool   `toml:"-"` // derived from BaseURL at load time
}

func Load(configPath string) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://api.hyperliquid.xyz",
	}

	// Resolve config path
	path := configPath
	if path == "" {
		path = os.Getenv("HYPERLIQUID_CONFIG")
	}
	if path == "" {
		home, _ := os.UserHomeDir()
		path = filepath.Join(home, ".config", "hyperliquid-pp-cli", "config.toml")
	}
	cfg.Path = path

	// Try to load config file
	data, err := os.ReadFile(path)
	if err == nil {
		if err := toml.Unmarshal(data, cfg); err != nil {
			return nil, fmt.Errorf("parsing config %s: %w", path, err)
		}
	}

	// Env var overrides

	// Label config-file-derived credentials so doctor can distinguish
	// "credentials persisted on disk" from "no credentials at all" — without
	// this, users who saved via set-token without an env var see a blank
	// auth_source and can't tell whether their config is being picked up.
	// The label is the literal "config" rather than "config:<path>"; the
	// config file path is exposed separately as report["config_path"], and
	// embedding it in auth_source leaks the user's home directory through
	// doctor's JSON envelope.
	if cfg.AuthSource == "" && (cfg.AuthHeaderVal != "") {
		cfg.AuthSource = "config"
	}

	// Base URL override (used by printing-press verify to point at mock/test servers)
	if v := os.Getenv("HYPERLIQUID_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}

	// Wallet defaults.
	if cfg.Wallet == "" {
		cfg.Wallet = "agent"
	}
	if cfg.AgentKeyPath == "" {
		if v := os.Getenv("HYPERLIQUID_AGENT_KEY"); v != "" {
			cfg.AgentKeyPath = v
		} else {
			home, _ := os.UserHomeDir()
			cfg.AgentKeyPath = filepath.Join(home, ".hyperliquid", "agent.key")
		}
	}
	// MainKeyPath has no default — the user must opt in by setting it. The
	// CLI also accepts HYPERLIQUID_MAIN_KEY env var (raw hex) as an alternative
	// that never touches disk.

	cfg.IsMainnet = !strings.Contains(cfg.BaseURL, "testnet")

	return cfg, nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) save() error {
	dir := filepath.Dir(c.Path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("creating config dir: %w", err)
	}
	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	return os.WriteFile(c.Path, data, 0o600)
}

// Ensure strings import is used
var _ = strings.ReplaceAll
