// Copyright 2026 mark-s. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cobratree

import (
	"os"
	"os/exec"
	"path/filepath"
)

// SiblingCLIPath resolves the companion CLI via sibling-of-executable,
// HYPERLIQUID_CLI_PATH env var, then PATH.
//
// We try both `hyperliquid` (the user-facing binary name we ship under) and
// `hyperliquid-pp-cli` (the press's default name) so this works whether the
// user built with `make build` (produces `hyperliquid`) or via the press's
// generator (produces `hyperliquid-pp-cli`).
func SiblingCLIPath() (string, error) {
	candidates := []string{"hyperliquid", "hyperliquid-pp-cli"}

	if exe, err := os.Executable(); err == nil {
		dir := filepath.Dir(exe)
		for _, name := range candidates {
			candidate := filepath.Join(dir, name)
			if _, err := os.Stat(candidate); err == nil {
				return candidate, nil
			}
		}
	}
	if v := os.Getenv("HYPERLIQUID_CLI_PATH"); v != "" {
		return v, nil
	}
	for _, name := range candidates {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	return "", exec.ErrNotFound
}
